[build-system]
requires = [
    "setuptools>=42",
    "pybind11>=2.10.0",
    "torch>=2.1.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "LidarAug"
version = "0.0.1"
dependencies = [
    "torch",
]

# target-version = "py37"
