name: CMake and Google Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [gcc]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: setup google test
      uses: Bacondish2023/setup-googletest@v1

    - name: Install GCC 13
      run: |
        sudo apt-get update && sudo apt-get install -y gcc-13 g++13
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 110 --slave /usr/bin/g++ g++ /usr/bin/g++-13 --slave /usr/bin/gcov gcov /usr/bin/gcov-13

    - name: Install CMake
      run: sudo apt-get update && sudo apt-get install -y cmake

    - name: Install Boost
      run: sudo apt-get update && sudo apt-get install -y libboost-all-dev

    - name: Install libtorch
      run: |
        wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-2.3.0%2Bcpu.zip
        unzip libtorch-cxx11-abi-shared-with-deps-2.3.0+cpu.zip -d /opt/

    - name: Create build directory
      run: mkdir build
      working-directory: ./cpp

    - name: Configure and build
      run: |
        cd build
        cmake -DBOOST_ROOT=/usr/include/boost -DCMAKE_PREFIX_PATH=/opt/libtorch ..
        make
      working-directory: ./cpp

    - name: Run Google Test
      run: |
        cd build
        ctest --output-on-failure
      working-directory: ./cpp
